name: 🧪 CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  integration:
    name: "${{ matrix.os }} / ${{ matrix.package-manager }} / node ${{ matrix.node-version }}"

    strategy:
      fail-fast: false
      matrix:
        node-version: [18, 20, 22]
        package-manager: [npm, yarn, pnpm]
        os: [ubuntu-latest]
        include:
          - os: macos-latest
            node-version: 18
            package-manager: npm
          - os: windows-latest
            node-version: 18
            package-manager: npm

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: pnpm
        if: matrix.package-manager == 'pnpm'
        run: |
          npm install -g pnpm
          pnpm install
          pnpm run build
        
      - name: yarn
        if: matrix.package-manager == 'yarn'
        run: |
          npm install -g yarn
          yarn
          yarn build
      
      - name: npm
        if: matrix.package-manager == 'npm'
        run: |
          npm install
          npm run build
