name: 🧪 CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  integration:
    name: "👀 (os: ${{ matrix.os }}, pm: ${{ matrix.package-manager }}, node: ${{ matrix.node-version }})"

    strategy:
      fail-fast: false
      matrix:
        node-version: [18, 20, 22]
        package-manager: [npm, yarn, pnpm]
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies (yarn)
        if: matrix.package-manager == 'yarn'
        run: yarn

      - name: Install dependencies (pnpm)
        if: matrix.package-manager == 'pnpm'
        run: pnpm install

      - name: Install dependencies (npm)
        if: matrix.package-manager == 'npm'
        run: npm install

      - name: Build (yarn)
        if: matrix.package-manager == 'yarn'
        run: yarn build

      - name: Build (pnpm)
        if: matrix.package-manager == 'pnpm'
        run: pnpm build

      - name: Build (npm)
        if: matrix.package-manager == 'npm'
        run: npm run build
